# define the shell to bash
SHELL := /bin/bash

# define the C/C++ compiler to use,default here is clang
CC = gcc-7
MPICC = mpicc
MPIRUN = mpirun --oversubscribe -np 4

test_sequential:
# 	tar -xvzf code.tar.gz
	cd knnring; make lib; cd ..
	cd knnring; cp lib/*.a inc/knnring.h ../; cd ..
	$(CC) tester.c knnring_sequential.a -o $@ -lm -lopenblas
	./test_sequential
	rm test_sequential


test_mpi:
# 	tar -xvzf code.tar.gz
	cd knnring; make lib; cd ..
	cd knnring; cp lib/*.a inc/knnring.h ../; cd ..
	$(MPICC) tester_mpi.c knnring_mpi.a -o $@ -lm -lopenblas
	$(MPIRUN) ./test_mpi
	rm test_mpi
